In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
loc = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_location/clean_id_loc_year_type.csv", 
                  encoding='cp1252')

In [4]:
inv = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_investment/inv00-19.csv", 
                  encoding='cp1252')

In [5]:
empf = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_employment/emp_agg_f.csv", 
                  encoding='cp1252')

In [6]:
empm = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_employment/emp_agg_m.csv", 
                  encoding='cp1252')

In [7]:
emp_total = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_employment/emp_agg_total.csv", 
                  encoding='cp1252')

In [8]:
ent = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_enterprises/ent99_19.csv", 
                  encoding='cp1252')

In [9]:
exp_ele = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_expenses/ele_exp00_19.csv", 
                  encoding='cp1252')

In [10]:
exp_com = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_expenses/com_exp00_19.csv", 
                  encoding='cp1252')

In [11]:
exp_inf = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_expenses/infotep_exp00_19.csv", 
                  encoding='cp1252')

In [12]:
exp_wat = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_expenses/water_exp00_19.csv", 
                  encoding='cp1252')

In [13]:
exp_tss = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_expenses/tss_exp00_19.csv", 
                  encoding='cp1252')

In [14]:
nav = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_naves/nav_agg_00_16.csv", 
                  encoding='cp1252')

In [15]:
nav

,code,buiilt00,ocu00,buiilt01,ocu01,buiilt02,ocu02,buiilt03,ocu03,buiilt04,...,buiilt12,ocu12,buiilt13,ocu13,buiilt14,ocu14,buiilt15,ocu15,buiilt16,ocu16
0,DOM-6NO,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,33356.00,33356.00
1,DOM-ALC,482462.00,482462.00,563307.0,531735.0,563307.6,531735.0,563307.0,523307.0,563307.0,...,583516.00,386345.12,619079.63,439920.97,619079.63,485938.61,619079.63,428063.29,563991.87,456251.54
2,DOM-ALT,202317.26,191273.93,202317.0,184043.0,211515.6,200515.6,239072.0,194592.0,239072.0,...,240312.07,138017.57,240312.07,138017.57,240312.07,172672.00,240312.07,172672.00,240312.07,172734.00
3,DOM-AND,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,270488.00,64500.00,270488,64500.00,64500.00,64500.00,64500.00,64500.00,64500.00,64500.00
4,DOM-ARM,254469.00,229066.00,275783.0,275783.0,275783.0,275783.0,275783.0,275783.0,337529.0,...,337529.00,235255.15,310078.93,283104.28,310078.93,279648.41,310078.93,279648.41,337333.20,314720.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,DOM-TAM,80000.00,20000.00,191724.0,191724.0,184879.0,165374.0,184879.0,184879.0,184879.0,...,388000.00,388000.00,688640,688640.00,688640.00,688640.00,656119.00,656119.00,824250.00,620403.00
83,DOM-VEG,1283873.00,1283873.00,1116683.0,1116683.0,1116683.0,1116683.0,1116683.0,1116683.0,1228505.0,...,1173226.00,920888.74,1122197.2,994814.98,1122197.20,1067969.53,1122197.00,1122197.00,1261076.26,1157306.67
84,DOM-VIS,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,506796.0,...,421816.00,421816.00,421816,421816.00,421834.00,421834.00,421834.00,421834.00,421834.00,421834.00
85,DOM-YAQ,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,200738.56,200738.56,200738.56,200738.56,200738.56,200738.56,200738.56,200738.56,200738.56,200738.56
86,DOM-ZOF,38000.00,38000.00,38000.0,38000.0,38000.0,38000.0,38000.0,22000.0,38000.0,...,0.00,0.00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [16]:
op = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_salary/sal_op_00_16.csv", 
                  encoding='cp1252')

In [17]:
tec = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_salary/sal_tec_00_16.csv", 
                  encoding='cp1252')

In [18]:
def f(df):
    #df.drop(df.columns.str.contains("par"), inplace = True)
    return df.drop(columns=df.columns[df.columns.str.contains("par")])

In [19]:
#databases = [empf, empm, emp_total, ent, exp_ele, exp_com, exp_inf, exp_wat, exp_tss, nav, op, tec]
databases = [empf, empm, emp_total, ent, exp_ele, exp_com, exp_inf, exp_wat, exp_tss, nav, op, tec]

In [20]:
sez = pd.merge(loc, f(inv), on="code", how="outer")

In [21]:
for database in databases: 
    sez = pd.merge(sez, f(database), on="code", how="outer")

In [22]:
sez = sez[sez["code"] != "DOM-ZFE"]

In [23]:
sez.fillna(0, inplace=True)

In [24]:
#Puts full year on the columns names 
def rename_columns(df):
    new_columns = []
    for col in df.columns:
        if col[-2:].isdigit() and not col[-4:].isdigit():
            new_columns.append(col[:-2] + "20" + col[-2:])  
        else:
            new_columns.append(col)
    df.columns = new_columns
    return df

In [25]:
sez = rename_columns(sez)

In [26]:
sez.rename(columns = {"ent2099": "ent1999"}, inplace = True)

In [27]:
filter_year = ["2017", "2018", "2018", "2019", "2020", "2021", "2022", "1999"]

pattern = "|".join(filter_year)
sez_filtered = sez.drop(columns = sez.columns[sez.columns.str.contains(pattern)])

In [28]:
 sez_filtered

,code,name,latitude,longitude,year,close,type,sez_id,origin,inv2000,...,sal_tec2006,sal_tec2007,sal_tec2008,sal_tec2010,sal_tec2011,sal_tec2012,sal_tec2013,sal_tec2014,sal_tec2015,sal_tec2016
0,DOM-6NO,Zona Franca 6 de Noviembre,18.434236,-70.077097,2016.0,0.0,private,1.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2500.00
1,DOM-ALC,Los Alcarrizos,18.521192,-70.050865,1990.0,0.0,public,2.0,1.0,19853638.95,...,2770.28,3446.06,2969.16,3389.04,3762.00,3197.77,3533.52,3852.34,4420.89,4293.00
2,DOM-ALT,Villa Altagracia,18.687048,-70.180632,1988.0,0.0,private,3.0,1.0,33900000.00,...,2167.86,3489.29,3026.84,2903.04,5212.50,4772.18,4996.25,5007.53,5640.68,5610.00
3,DOM-AND,Andres,18.442336,-69.649780,2009.0,0.0,private,4.0,1.0,0.00,...,0.00,0.00,0.00,3675.25,3654.00,6025.00,5077.00,7045.37,6936.53,7100.00
4,DOM-ARM,La Armeria,18.421294,-70.117660,1990.0,0.0,public,5.0,1.0,8620740.19,...,2878.17,1954.00,2551.00,3893.25,3359.33,3131.93,4402.00,3956.30,4300.90,4187.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,DOM-VEG,La Vega,19.246732,-70.556490,1987.0,0.0,public,91.0,1.0,45018217.52,...,2891.53,3836.31,2984.12,3190.84,3356.29,3686.81,3737.21,4189.40,4754.71,4671.84
91,DOM-VER,Luperon Verde,19.793250,-70.680905,2019.0,0.0,private,92.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
92,DOM-VIS,Bella Vista,18.613215,-69.708447,2004.0,0.0,private,93.0,1.0,0.00,...,4500.00,0.00,4569.00,5375.00,4698.00,6863.00,6433.17,7015.64,4450.00,4500.00
93,DOM-YAQ,Parque Industrial y de Servicios Yaque,19.469724,-70.714373,2010.0,0.0,private,94.0,1.0,0.00,...,0.00,0.00,0.00,3439.60,4800.00,3417.45,3807.43,2897.10,3996.96,5841.01
95,DOM-ZOF,Zofinma (Mao),19.553957,-71.091628,1993.0,2006.0,private,95.0,1.0,413004.00,...,4000.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [29]:
#sez_filtered.columns[sez_filtered.columns.str.contains(year)]

In [30]:
sez_filtered.to_csv("sez_aggregated.csv", index=False)

In [31]:
sez.columns

Index(['code', 'name', 'latitude', 'longitude', 'year', 'close', 'type',
       'sez_id', 'origin ', 'inv2000',
       ...
       'sal_tec2007', 'sal_tec2008', 'sal_tec2019', 'sal_tec2010',
       'sal_tec2011', 'sal_tec2012', 'sal_tec2013', 'sal_tec2014',
       'sal_tec2015', 'sal_tec2016'],
      dtype='object', length=362)

In [32]:
sez.tail(10)

,code,name,latitude,longitude,year,close,type,sez_id,origin,inv2000,...,sal_tec2007,sal_tec2008,sal_tec2019,sal_tec2010,sal_tec2011,sal_tec2012,sal_tec2013,sal_tec2014,sal_tec2015,sal_tec2016
85,DOM-SLI,Parque Tecnologico de Santiago,19.446254,-70.639953,1993.0,0.0,private,86.0,1.0,5324144.00,...,3424.13,3925.00,3085.71,2990.04,3202.71,3516.67,4145.83,6693.75,5641.67,6605.00
86,DOM-SUN,Parque Industrial Zona Franca Sunsea,0.000000,0.000000,2016.0,2019.0,private,87.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5000.00
87,DOM-SUR,Zona Franca Ind. Del Sur,0.000000,0.000000,2014.0,0.0,private,88.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5624.00,0.00,0.00
88,DOM-TAL,Intercontinental,18.560544,-70.070350,2015.0,0.0,private,89.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5736.96,5800.00
89,DOM-TAM,Tamboril,19.481426,-70.633332,1997.0,0.0,private,90.0,1.0,220900.00,...,2833.33,3575.00,2962.75,3116.93,3286.85,4650.03,4100.00,4103.83,4749.78,4563.17
90,DOM-VEG,La Vega,19.246732,-70.556490,1987.0,0.0,public,91.0,1.0,45018217.52,...,3836.31,2984.12,3021.27,3190.84,3356.29,3686.81,3737.21,4189.40,4754.71,4671.84
91,DOM-VER,Luperon Verde,19.793250,-70.680905,2019.0,0.0,private,92.0,1.0,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
92,DOM-VIS,Bella Vista,18.613215,-69.708447,2004.0,0.0,private,93.0,1.0,0.00,...,0.00,4569.00,4615.00,5375.00,4698.00,6863.00,6433.17,7015.64,4450.00,4500.00
93,DOM-YAQ,Parque Industrial y de Servicios Yaque,19.469724,-70.714373,2010.0,0.0,private,94.0,1.0,0.00,...,0.00,0.00,0.00,3439.60,4800.00,3417.45,3807.43,2897.10,3996.96,5841.01
95,DOM-ZOF,Zofinma (Mao),19.553957,-71.091628,1993.0,2006.0,private,95.0,1.0,413004.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [33]:
#inv = pd.read_csv("/Users/hendrixperalta/Desktop/Research Data Manipulation/research_data/sez_investment/inv00-19.csv", 
                  #encoding='cp1252')